# Generated by Django 3.2.9 on 2021-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.JSONField()),
                ('data', models.JSONField()),
                ('file', models.JSONField()),
                ('form', models.JSONField()),
            ],
        ),
    ]
