# Generated by Django 3.2.9 on 2021-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wreccode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='args',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='data',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='file',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='form',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
