# Generated by Django 3.2.9 on 2021-12-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wreccode', '0003_auto_20211218_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='args',
            field=models.JSONField(default={}),
        ),
    ]
