# Generated by Django 3.2.9 on 2021-12-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wreccode', '0004_alter_responses_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='data',
            field=models.CharField(default=dict, max_length=12),
        ),
    ]
