# Generated by Django 3.2.9 on 2021-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wreccode', '0005_alter_responses_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
