# Generated by Django 3.2.9 on 2021-12-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wreccode', '0007_auto_20211218_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='data',
            field=models.IntegerField(default=dict),
        ),
        migrations.AlterField(
            model_name='responses',
            name='file',
            field=models.IntegerField(default={}),
        ),
        migrations.AlterField(
            model_name='responses',
            name='form',
            field=models.IntegerField(default={}),
        ),
    ]
