# Generated by Django 3.2.9 on 2021-12-01 23:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('First_Name', models.CharField(max_length=20, null=True)),
                ('Last_Name', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(error_messages={'error': 'This field already exist'}, max_length=50, primary_key=True, serialize=False)),
                ('Phone_Number', models.CharField(max_length=11, null=True)),
                ('Country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('Password1', models.CharField(max_length=20, null=True)),
                ('Confirm_Password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(max_length=11)),
                ('Branch_name', models.CharField(max_length=50)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
